const {app,BrowserWindow}=require('electron');const path=require('path'),fs=require('fs'),assert=require('assert');const {registerIpcHandlers}=require('../dist/main/ipc');
app.setPath('userData',path.join(__dirname,'profile'));app.commandLine.appendSwitch('enable-unsafe-swiftshader');const root=path.resolve(__dirname,'..'),fixtures=path.join(__dirname,'fixtures');let nextFile='source.aiff';
registerIpcHandlers(async()=>({canceled:false,filePaths:[path.join(fixtures,nextFile)]}));
app.whenReady().then(async()=>{try{
const win=new BrowserWindow({show:false,width:1280,height:900,webPreferences:{preload:path.join(root,'dist/main/preload.js')}});win.webContents.on('console-message',e=>{if(e.level==='warning'||e.level==='error')console.log('RENDERER',e.message)});
await win.loadFile(path.join(root,'src/renderer/index.html'));const run=s=>win.webContents.executeJavaScript(s);
const click=id=>run(`document.getElementById('${id}').click()`);
const ready=async()=>{for(let i=0;i<300;i++){await new Promise(r=>setTimeout(r,100));if(await run("document.getElementById('loading-indicator').style.display==='none'"))return;}throw Error('UI loading timed out');};
await click('open-file-btn');await ready();assert((await run("document.getElementById('file-details').textContent")).includes('24-bit'));assert((await run("document.getElementById('file-details').textContent")).includes('44.1 kHz'));
await run("document.getElementById('color-scheme').value='3band';document.getElementById('color-scheme').dispatchEvent(new Event('change'))");
assert(await run("document.getElementById('compare-bar').hidden"));await click('compare-btn');assert(await run("!document.getElementById('compare-bar').hidden"));assert(await run("!document.getElementById('compare-split')"));nextFile='alternate.wav';await click('open-b-btn');await ready();assert(await run("!document.getElementById('comparison-section').hidden"));assert((await run("document.getElementById('file-details').textContent")).includes('48.0 kHz'));assert.equal(await run("document.getElementById('freq-axis').children.length"),12);
await run("document.getElementById('timeline-slider').value='30';document.getElementById('timeline-slider').dispatchEvent(new Event('input'))");await click('play-btn');await new Promise(r=>setTimeout(r,100));await click('slot-a');assert(await run("document.getElementById('play-btn').classList.contains('playing')"));const position=Number(await run("document.getElementById('timeline-slider').value"));assert(position>22&&position<29,position);await click('play-btn');
await run("(()=>{const c=document.getElementById('comparison-canvas'),r=c.getBoundingClientRect();c.dispatchEvent(new PointerEvent('pointermove',{clientX:r.left+r.width*.95,clientY:r.top+r.height*.5}));})()");assert((await run("document.getElementById('comparison-tooltip').textContent")).includes('No data'));
await click('zoom-in');assert.equal(await run("document.getElementById('zoom-level').textContent"),'2.0×');await click('zoom-reset');
await run("document.getElementById('fft-size').value='4096';document.getElementById('fft-size').dispatchEvent(new Event('change'))");await ready();await click('slot-b');assert((await run("document.getElementById('analysis-details').textContent")).includes('4096'));await click('slot-a');assert((await run("document.getElementById('analysis-details').textContent")).includes('4096'));
// A lost WebGL context (GPU reset, sleep) must be rebuilt and the spectrum redrawn.
const brightest=await run(`new Promise(resolve=>{const c=document.getElementById('spectrogram-canvas'),gl=c.getContext('webgl'),ext=gl.getExtension('WEBGL_lose_context');setTimeout(()=>resolve(-1),3000);c.addEventListener('webglcontextlost',()=>setTimeout(()=>ext.restoreContext()),{once:true});c.addEventListener('webglcontextrestored',()=>setTimeout(()=>{const px=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,px);let max=0;for(let i=0;i<px.length;i++)if(i%4!==3&&px[i]>max)max=px[i];resolve(max);}),{once:true});ext.loseContext();})`);assert(brightest>100,'spectrogram redrawn after context restore: '+brightest);
const glError=await run("document.getElementById('spectrogram-canvas').getContext('webgl').getError()");assert.equal(glError,0);
fs.writeFileSync(path.join(__dirname,'comparison.png'),(await win.webContents.capturePage()).toPNG());
const saved=new Promise(r=>win.webContents.session.once('will-download',(_,item)=>{item.setSavePath(path.join(__dirname,'comparison-export.png'));item.once('done',(_,s)=>r(s));}));await click('save-btn');assert.equal(await saved,'completed');
// Real filesystem-backed File through preload bridge, then drop on loaded plot.
win.webContents.debugger.attach('1.3');await run("const input=document.createElement('input');input.type='file';input.id='qa-file';input.hidden=true;document.body.append(input)");const {root:dom}=await win.webContents.debugger.sendCommand('DOM.getDocument');const {nodeId}=await win.webContents.debugger.sendCommand('DOM.querySelector',{nodeId:dom.nodeId,selector:'#qa-file'});await win.webContents.debugger.sendCommand('DOM.setFileInputFiles',{nodeId,files:[path.join(fixtures,'lossless.m4a')]});await run("(()=>{const t=new DataTransfer();t.items.add(document.getElementById('qa-file').files[0]);document.getElementById('spectrogram-canvas').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:t}));})()");await ready();assert((await run("document.getElementById('file-details').textContent")).includes('ALAC'));
assert((await run(`window.api.readFile(${JSON.stringify(path.join(fixtures,'reference.wav'))}).then(()=>'read',e=>e.message)`)).endsWith('Open the file with Open file or drag and drop.'));
nextFile='invalid.wav';await click('open-b-btn');await ready();assert.equal(await run("document.getElementById('slot-b-name').textContent"),'alternate.wav');assert((await run("document.getElementById('status').textContent")).includes('Could not read'));
win.setSize(720,600);await new Promise(r=>setTimeout(r,100));assert(await run("document.body.scrollWidth===innerWidth"));fs.writeFileSync(path.join(__dirname,'narrow.png'),(await win.webContents.capturePage()).toPNG());
await click('compare-btn');assert(await run("document.getElementById('compare-bar').hidden && document.getElementById('comparison-section').hidden"));await click('compare-btn');assert(await run("!document.getElementById('comparison-section').hidden"));console.log('PASS A/B playback, aligned rates/durations, shared FFT, zoom, Tri-band WebGL, PNG export, ALAC drop, invalid replacement and narrow layout');app.quit();
}catch(e){console.error(e);app.exit(1)}});
